#!/usr/bin/env python3
"""
Re-research universities that failed validation or were deleted.
"""

RERESEARCH_UNIVERSITIES = [
    # 51 failing validation
    "Adelphi University",
    "Arizona State University",
    "California State University, Long Beach",
    "Clark University",
    "Clarkson University",
    "Colorado School of Mines",
    "Colorado State University",
    "DePaul University",
    "Duquesne University",
    "East Carolina University",
    "Elon University",
    "Hofstra University",
    "Iowa State University",
    "Kansas State University",
    "Loyola University Chicago",
    "Missouri University of Science and Technology",
    "New Jersey Institute of Technology",
    "Ohio University",
    "Oklahoma State University",
    "Rochester Institute of Technology",
    "Seattle University",
    "Seton Hall University",
    "Simmons University",
    "Texas A&M University",
    "The Catholic University of America",
    "University of Alabama",
    "University of Arkansas",
    "University of California, Merced",
    "University of Central Florida",
    "University of Cincinnati",
    "University of Dayton",
    "University of Hawaii at Manoa",
    "University of Kansas",
    "University of Kentucky",
    "University of La Verne",
    "University of Louisville",
    "University of Massachusetts Lowell",
    "University of Missouri",
    "University of Nebraska-Lincoln",
    "University of Nevada, Reno",
    "University of New Hampshire",
    "University of Oklahoma",
    "University of Rhode Island",
    "University of San Francisco",
    "University of St. Thomas (Minnesota)",
    "University of Tennessee, Knoxville",
    "University of the Pacific",
    "University of Tulsa",
    "Washington University in St. Louis",
    "Worcester Polytechnic Institute",
    "Yeshiva University",
    # 15 deleted corrupted files
    "Bowling Green State University",
    "Georgia State University",
    "Mercer University",
    "Morgan State University",
    "Pace University",
    "Samford University",
    "SUNY Binghamton University",
    "Tennessee Tech University",
    "University of Akron",
    "University of Maine",
    "University of Mississippi",
    "University of North Dakota",
    "University of Wyoming",
    "Wayne State University",
    "West Virginia University",
]

if __name__ == "__main__":
    print(f"Total universities to re-research: {len(RERESEARCH_UNIVERSITIES)}")
    for i, uni in enumerate(RERESEARCH_UNIVERSITIES, 1):
        print(f"{i}. {uni}")
